// City Geo Data - Coordinates, Wikipedia URLs, and Google Maps data for all service areas
// Used by CityGeoSection component for geo-targeting signals (maps, authority links)

export interface CityGeoData {
  slug: string;
  city: string;
  state: string;
  stateFullName: string;
  latitude: number;
  longitude: number;
  wikipediaUrl: string;
  googleMapsUrl: string;
  googleMapsEmbedQuery: string;
}

// All service area cities with their geo data
export const CITY_GEO_DATA: CityGeoData[] = [
  // === MECKLENBURG COUNTY ===
  {
    slug: 'charlotte-nc',
    city: 'Charlotte',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2271,
    longitude: -80.8431,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Charlotte,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Charlotte,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Charlotte+NC',
  },
  {
    slug: 'huntersville-nc',
    city: 'Huntersville',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.4107,
    longitude: -80.8429,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Huntersville,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Huntersville,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Huntersville+NC',
  },
  {
    slug: 'cornelius-nc',
    city: 'Cornelius',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.4868,
    longitude: -80.8601,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cornelius,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Cornelius,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Cornelius+NC',
  },
  {
    slug: 'davidson-nc',
    city: 'Davidson',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.4993,
    longitude: -80.8487,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Davidson,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Davidson,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Davidson+NC',
  },
  {
    slug: 'matthews-nc',
    city: 'Matthews',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.1168,
    longitude: -80.7237,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Matthews,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Matthews,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Matthews+NC',
  },
  {
    slug: 'mint-hill-nc',
    city: 'Mint Hill',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.1796,
    longitude: -80.6468,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mint_Hill,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Mint+Hill,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Mint+Hill+NC',
  },
  {
    slug: 'pineville-nc',
    city: 'Pineville',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.0832,
    longitude: -80.8923,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Pineville,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Pineville,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Pineville+NC',
  },

  // === CABARRUS COUNTY ===
  {
    slug: 'concord-nc',
    city: 'Concord',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.4088,
    longitude: -80.5795,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Concord,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Concord,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Concord+NC',
  },
  {
    slug: 'kannapolis-nc',
    city: 'Kannapolis',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.4874,
    longitude: -80.6217,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Kannapolis,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Kannapolis,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Kannapolis+NC',
  },
  {
    slug: 'harrisburg-nc',
    city: 'Harrisburg',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.3246,
    longitude: -80.6534,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Harrisburg,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Harrisburg,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Harrisburg+NC',
  },
  {
    slug: 'mount-pleasant-nc',
    city: 'Mount Pleasant',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.3999,
    longitude: -80.4357,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mount_Pleasant,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Mount+Pleasant,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Mount+Pleasant+NC',
  },
  {
    slug: 'midland-nc',
    city: 'Midland',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2271,
    longitude: -80.5004,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Midland,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Midland,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Midland+NC',
  },
  {
    slug: 'locust-nc',
    city: 'Locust',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2610,
    longitude: -80.4215,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Locust,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Locust,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Locust+NC',
  },

  // === UNION COUNTY ===
  {
    slug: 'monroe-nc',
    city: 'Monroe',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 34.9854,
    longitude: -80.5495,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Monroe,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Monroe,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Monroe+NC',
  },
  {
    slug: 'indian-trail-nc',
    city: 'Indian Trail',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.0768,
    longitude: -80.6693,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Indian_Trail,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Indian+Trail,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Indian+Trail+NC',
  },
  {
    slug: 'waxhaw-nc',
    city: 'Waxhaw',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 34.9243,
    longitude: -80.7434,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Waxhaw,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Waxhaw,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Waxhaw+NC',
  },
  {
    slug: 'stallings-nc',
    city: 'Stallings',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.0907,
    longitude: -80.6862,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Stallings,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Stallings,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Stallings+NC',
  },
  {
    slug: 'weddington-nc',
    city: 'Weddington',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.0224,
    longitude: -80.7578,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Weddington,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Weddington,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Weddington+NC',
  },
  {
    slug: 'marvin-nc',
    city: 'Marvin',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 34.9921,
    longitude: -80.8143,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Marvin,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Marvin,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Marvin+NC',
  },
  {
    slug: 'wesley-chapel-nc',
    city: 'Wesley Chapel',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.0071,
    longitude: -80.6748,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Wesley_Chapel,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Wesley+Chapel,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Wesley+Chapel+NC',
  },
  {
    slug: 'wingate-nc',
    city: 'Wingate',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 34.9843,
    longitude: -80.4493,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Wingate,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Wingate,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Wingate+NC',
  },
  {
    slug: 'fairview-nc',
    city: 'Fairview',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.0499,
    longitude: -80.5843,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Fairview,_Union_County,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Fairview,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Fairview+NC',
  },
  {
    slug: 'hemby-bridge-nc',
    city: 'Hemby Bridge',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.1013,
    longitude: -80.6268,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Hemby_Bridge,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Hemby+Bridge,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Hemby+Bridge+NC',
  },
  {
    slug: 'unionville-nc',
    city: 'Unionville',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.0874,
    longitude: -80.5082,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Unionville,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Unionville,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Unionville+NC',
  },

  // === GASTON COUNTY ===
  {
    slug: 'gastonia-nc',
    city: 'Gastonia',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2621,
    longitude: -81.1873,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Gastonia,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Gastonia,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Gastonia+NC',
  },
  {
    slug: 'mt-holly-nc',
    city: 'Mt Holly',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2982,
    longitude: -81.0159,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mount_Holly,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Mount+Holly,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Mount+Holly+NC',
  },
  {
    slug: 'belmont-nc',
    city: 'Belmont',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2430,
    longitude: -81.0387,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Belmont,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Belmont,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Belmont+NC',
  },
  {
    slug: 'cramerton-nc',
    city: 'Cramerton',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2382,
    longitude: -81.0748,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cramerton,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Cramerton,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Cramerton+NC',
  },
  {
    slug: 'lowell-nc',
    city: 'Lowell',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2682,
    longitude: -81.1026,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Lowell,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Lowell,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Lowell+NC',
  },
  {
    slug: 'dallas-nc',
    city: 'Dallas',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.3165,
    longitude: -81.1762,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Dallas,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Dallas,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Dallas+NC',
  },
  {
    slug: 'cherryville-nc',
    city: 'Cherryville',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.3793,
    longitude: -81.3793,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Cherryville,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Cherryville,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Cherryville+NC',
  },
  {
    slug: 'bessemer-city-nc',
    city: 'Bessemer City',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2849,
    longitude: -81.2837,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Bessemer_City,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Bessemer+City,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Bessemer+City+NC',
  },

  // === IREDELL COUNTY ===
  {
    slug: 'mooresville-nc',
    city: 'Mooresville',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.5849,
    longitude: -80.8101,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Mooresville,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Mooresville,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Mooresville+NC',
  },
  {
    slug: 'statesville-nc',
    city: 'Statesville',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.7826,
    longitude: -80.8873,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Statesville,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Statesville,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Statesville+NC',
  },

  // === LINCOLN COUNTY ===
  {
    slug: 'denver-nc',
    city: 'Denver',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.5318,
    longitude: -81.0298,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Denver,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Denver,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Denver+NC',
  },
  {
    slug: 'lincolnton-nc',
    city: 'Lincolnton',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.4740,
    longitude: -81.2545,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Lincolnton,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Lincolnton,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Lincolnton+NC',
  },
  {
    slug: 'maiden-nc',
    city: 'Maiden',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.5754,
    longitude: -81.2118,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Maiden,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Maiden,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Maiden+NC',
  },

  // === LAKE NORMAN AREA ===
  {
    slug: 'lake-norman',
    city: 'Lake Norman',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.5107,
    longitude: -80.9190,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Lake_Norman',
    googleMapsUrl: 'https://www.google.com/maps/place/Lake+Norman,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Lake+Norman+NC',
  },
  {
    slug: 'sherrills-ford-nc',
    city: 'Sherrills Ford',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.6143,
    longitude: -80.9876,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Sherrills_Ford,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Sherrills+Ford,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Sherrills+Ford+NC',
  },
  {
    slug: 'terrell-nc',
    city: 'Terrell',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.5860,
    longitude: -80.9654,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Terrell,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Terrell,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Terrell+NC',
  },

  // === CATAWBA COUNTY ===
  {
    slug: 'hickory-nc',
    city: 'Hickory',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.7332,
    longitude: -81.3412,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Hickory,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Hickory,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Hickory+NC',
  },
  {
    slug: 'newton-nc',
    city: 'Newton',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.6696,
    longitude: -81.2215,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Newton,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Newton,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Newton+NC',
  },
  {
    slug: 'conover-nc',
    city: 'Conover',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.7071,
    longitude: -81.2187,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Conover,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Conover,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Conover+NC',
  },
  {
    slug: 'claremont-nc',
    city: 'Claremont',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.7135,
    longitude: -81.1465,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Claremont,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Claremont,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Claremont+NC',
  },

  // === STANLY COUNTY ===
  {
    slug: 'albemarle-nc',
    city: 'Albemarle',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.3502,
    longitude: -80.2001,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Albemarle,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Albemarle,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Albemarle+NC',
  },
  {
    slug: 'oakboro-nc',
    city: 'Oakboro',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2254,
    longitude: -80.3290,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Oakboro,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Oakboro,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Oakboro+NC',
  },
  {
    slug: 'norwood-nc',
    city: 'Norwood',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2190,
    longitude: -80.1193,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Norwood,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Norwood,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Norwood+NC',
  },

  // === CLEVELAND COUNTY ===
  {
    slug: 'shelby-nc',
    city: 'Shelby',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2924,
    longitude: -81.5356,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Shelby,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Shelby,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Shelby+NC',
  },
  {
    slug: 'kings-mountain-nc',
    city: 'Kings Mountain',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.2451,
    longitude: -81.3412,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Kings_Mountain,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Kings+Mountain,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Kings+Mountain+NC',
  },

  // === ROWAN COUNTY ===
  {
    slug: 'salisbury-nc',
    city: 'Salisbury',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.6710,
    longitude: -80.4743,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Salisbury,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Salisbury,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Salisbury+NC',
  },
  {
    slug: 'china-grove-nc',
    city: 'China Grove',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.5693,
    longitude: -80.5818,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/China_Grove,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/China+Grove,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+China+Grove+NC',
  },
  {
    slug: 'landis-nc',
    city: 'Landis',
    state: 'NC',
    stateFullName: 'North_Carolina',
    latitude: 35.5460,
    longitude: -80.6109,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Landis,_North_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Landis,+NC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Landis+NC',
  },

  // === SOUTH CAROLINA - YORK COUNTY ===
  {
    slug: 'rock-hill-sc',
    city: 'Rock Hill',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 34.9249,
    longitude: -81.0251,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Rock_Hill,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Rock+Hill,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Rock+Hill+SC',
  },
  {
    slug: 'fort-mill-sc',
    city: 'Fort Mill',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 35.0074,
    longitude: -80.9453,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Fort_Mill,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Fort+Mill,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Fort+Mill+SC',
  },
  {
    slug: 'tega-cay-sc',
    city: 'Tega Cay',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 35.0240,
    longitude: -81.0279,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Tega_Cay,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Tega+Cay,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Tega+Cay+SC',
  },
  {
    slug: 'clover-sc',
    city: 'Clover',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 35.1112,
    longitude: -81.2265,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Clover,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Clover,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Clover+SC',
  },
  {
    slug: 'york-sc',
    city: 'York',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 34.9943,
    longitude: -81.2421,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/York,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/York,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+York+SC',
  },
  {
    slug: 'lake-wylie-sc',
    city: 'Lake Wylie',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 35.1068,
    longitude: -81.0626,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Lake_Wylie,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Lake+Wylie,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Lake+Wylie+SC',
  },

  // === SOUTH CAROLINA - LANCASTER COUNTY ===
  {
    slug: 'indian-land-sc',
    city: 'Indian Land',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 34.9596,
    longitude: -80.8943,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Indian_Land,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Indian+Land,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Indian+Land+SC',
  },
  {
    slug: 'lancaster-sc',
    city: 'Lancaster',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 34.7204,
    longitude: -80.7709,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Lancaster,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Lancaster,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Lancaster+SC',
  },

  // === CHESTER COUNTY SC ===
  {
    slug: 'chester-sc',
    city: 'Chester',
    state: 'SC',
    stateFullName: 'South_Carolina',
    latitude: 34.7054,
    longitude: -81.2143,
    wikipediaUrl: 'https://en.wikipedia.org/wiki/Chester,_South_Carolina',
    googleMapsUrl: 'https://www.google.com/maps/place/Chester,+SC',
    googleMapsEmbedQuery: 'Best+Roofing+Now+Chester+SC',
  },
];

// Lookup by slug
const geoDataMap = new Map(CITY_GEO_DATA.map(c => [c.slug, c]));

export function getCityGeoData(citySlug: string): CityGeoData | null {
  return geoDataMap.get(citySlug) || null;
}

// Extract city slug from page slug like "roof-repair-huntersville-nc" → "huntersville-nc"
// or "commercial-roofing-fort-mill-sc" → "fort-mill-sc"
export function getCityFromPageSlug(pageSlug: string): CityGeoData | null {
  // Try to find matching city by checking if the page slug ends with the city slug
  for (const city of CITY_GEO_DATA) {
    if (pageSlug.endsWith(city.slug)) {
      return city;
    }
  }

  // Special cases for Lake Norman pages
  if (pageSlug.includes('lake-norman')) {
    return getCityGeoData('lake-norman');
  }

  return null;
}

// Get Google Maps embed URL for a city (free, no API key)
export function getGoogleMapsEmbedUrl(city: CityGeoData): string {
  return `https://www.google.com/maps?q=${city.googleMapsEmbedQuery}&output=embed`;
}

// Get Google Maps directions URL from the business to the city
export function getDirectionsUrl(city: CityGeoData): string {
  const destination = encodeURIComponent(`${city.city}, ${city.state}`);
  return `https://www.google.com/maps/dir/Best+Roofing+Now,+10130+Mallard+Creek+Rd+Suite+300,+Charlotte,+NC+28262/${destination}`;
}
