/**
 * Build-time script to generate a static set of known WordPress blog post slugs.
 * Used by the middleware to validate blog redirects (only redirect known slugs,
 * not arbitrary paths, so unknown URLs properly 404).
 *
 * Usage: npx tsx scripts/generate-blog-slugs.ts
 * Runs automatically via the "prebuild" npm script.
 */

import * as fs from 'fs';
import * as path from 'path';

const WP_API_URL = 'https://cms.bestroofingnow.com/wp-json/wp/v2';

async function fetchAllSlugs(): Promise<string[]> {
  const allSlugs: string[] = [];
  let page = 1;
  let hasMore = true;

  while (hasMore) {
    const res = await fetch(`${WP_API_URL}/posts?per_page=100&page=${page}&_fields=slug`);
    if (!res.ok) break;

    const posts: { slug: string }[] = await res.json();
    if (posts.length === 0) {
      hasMore = false;
    } else {
      allSlugs.push(...posts.map((p) => p.slug));
      page++;
    }
  }

  return allSlugs;
}

async function main() {
  console.log('Fetching blog slugs from WordPress...');
  const slugs = await fetchAllSlugs();
  console.log(`Found ${slugs.length} blog post slugs.`);

  const outputPath = path.join(__dirname, '..', 'src', 'lib', 'blog-slugs.ts');
  const content = `// Auto-generated by scripts/generate-blog-slugs.ts
// Do not edit manually. Run: npx tsx scripts/generate-blog-slugs.ts
// Last generated: ${new Date().toISOString()}

export const KNOWN_BLOG_SLUGS = new Set([
${slugs.map((s) => `  '${s}',`).join('\n')}
]);
`;

  fs.writeFileSync(outputPath, content, 'utf8');
  console.log(`Written ${slugs.length} slugs to ${outputPath}`);
}

main().catch(console.error);
